export enum ModalKey {
  CREATE_CHANNEL = 'CREATE_CHANNEL',
  EDIT_CHANNEL = 'EDIT_CHANNEL',
  DELETE_CHANNEL = 'DELETE_CHANNEL',
  LEAVE_CHANNEL = 'LEAVE_CHANNEL',
  ARCHIVE_CHANNEL = 'ARCHIVE_CHANNEL',
  CREATE_TEAM = 'CREATE_TEAM',
  EDIT_TEAM = 'EDIT_TEAM',
  LEAVE_TEAM = 'LEAVE_TEAM',
  ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  UNPIN_MESSAGE = 'UNPIN_MESSAGE',
  LIST_USER_REACTION = 'LIST_USER_REACTION',
  MARKDOWN_GUIDE = 'MARKDOWN_GUIDE',
  UN_SAVED_MESSAGE = 'UN_SAVED_MESSAGE',
  UPDATE_STATUS = 'UPDATE_STATUS',
  CONFIRM_SKILL = 'CONFIRM_SKILL',
  SKILL_LIST = 'SKILL_LIST'
}
